packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react19:
    react: ^19.0.3
    react-dom: ^19.0.3
    "@types/react": ^19.0.1
    "@types/react-dom": ^19.0.2

  tanstack-start:
    "@tanstack/react-router": ^1.121.0
    "@tanstack/react-router-devtools": ^1.121.0
    "@tanstack/react-start": ^1.121.0

  remix:
    "@remix-run/dev": ^2.16.5
    "@remix-run/node": ^2.16.5
    "@remix-run/react": ^2.16.5
    "@remix-run/serve": ^2.16.5

  next:
    next: ^16.0.10

  prisma:
    prisma: ^6.12.0
    "@prisma/client": ^6.12.0
    "@prisma/adapter-pg": ^6.12.0

catalog:
  react-datepicker: ^8.3.0

overrides:
  next: ^16
