packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.1
    "@types/react-dom": ^19.0.2

  tanstack-start:
    "@tanstack/react-router": ^1.136.8
    "@tanstack/react-router-devtools": ^1.136.8
    "@tanstack/react-start": ^1.136.8

  remix:
    "@remix-run/dev": ^2.16.5
    "@remix-run/node": ^2.16.5
    "@remix-run/react": ^2.16.5
    "@remix-run/serve": ^2.16.5

  next:
    next: ^16

  prisma:
    prisma: ^6.19.0
    "@prisma/client": ^6.19.0
    "@prisma/adapter-pg": ^6.19.0

  tailwind:
    tailwindcss: ^4.1.17
    "@tailwindcss/postcss": ^4.1.17
    "@tailwindcss/vite": ^4.1.17

catalog:
  react-datepicker: ^8.3.0

overrides:
  next: ^16
