/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminSplatImport } from './routes/admin.$'

// Create/Update Routes

const AdminSplatRoute = AdminSplatImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/admin/$': typeof AdminSplatRoute
}

export interface FileRoutesByTo {
  '/admin/$': typeof AdminSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/admin/$': typeof AdminSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/admin/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin/$'
  id: '__root__' | '/admin/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/admin/$"
      ]
    },
    "/admin/$": {
      "filePath": "admin.$.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
