/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminCustomRouteImport } from './routes/admin.custom'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as ApiUsersExportRouteImport } from './routes/api/users.export'
import { Route as ApiPostsExportRouteImport } from './routes/api/posts.export'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin.$'

const AdminCustomRoute = AdminCustomRouteImport.update({
  id: '/admin/custom',
  path: '/admin/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersExportRoute = ApiUsersExportRouteImport.update({
  id: '/api/users/export',
  path: '/api/users/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsExportRoute = ApiPostsExportRouteImport.update({
  id: '/api/posts/export',
  path: '/api/posts/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin/$': typeof AdminSplatRoute
  '/admin/custom': typeof AdminCustomRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/posts/export': typeof ApiPostsExportRoute
  '/api/users/export': typeof ApiUsersExportRoute
}
export interface FileRoutesByTo {
  '/admin/$': typeof AdminSplatRoute
  '/admin/custom': typeof AdminCustomRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/posts/export': typeof ApiPostsExportRoute
  '/api/users/export': typeof ApiUsersExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin/$': typeof AdminSplatRoute
  '/admin/custom': typeof AdminCustomRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/posts/export': typeof ApiPostsExportRoute
  '/api/users/export': typeof ApiUsersExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin/$'
    | '/admin/custom'
    | '/api/admin/$'
    | '/api/posts/export'
    | '/api/users/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/$'
    | '/admin/custom'
    | '/api/admin/$'
    | '/api/posts/export'
    | '/api/users/export'
  id:
    | '__root__'
    | '/admin/$'
    | '/admin/custom'
    | '/api/admin/$'
    | '/api/posts/export'
    | '/api/users/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminCustomRoute: typeof AdminCustomRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
  ApiPostsExportRoute: typeof ApiPostsExportRoute
  ApiUsersExportRoute: typeof ApiUsersExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/custom': {
      id: '/admin/custom'
      path: '/admin/custom'
      fullPath: '/admin/custom'
      preLoaderRoute: typeof AdminCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/export': {
      id: '/api/users/export'
      path: '/api/users/export'
      fullPath: '/api/users/export'
      preLoaderRoute: typeof ApiUsersExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/export': {
      id: '/api/posts/export'
      path: '/api/posts/export'
      fullPath: '/api/posts/export'
      preLoaderRoute: typeof ApiPostsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminCustomRoute: AdminCustomRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
  ApiPostsExportRoute: ApiPostsExportRoute,
  ApiUsersExportRoute: ApiUsersExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
