name: Release

on:
  push:
    branches:
      - main
      - v[0-9]+

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Create Release Pull Request or Publish (${{ github.ref_name }})
        uses: changesets/action@v1
        with:
          version: pnpm changeset-version
          publish: pnpm publish-packages
          title: ${{github.ref_name}} — Version Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
