name: Reset database

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  reset-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Create .env file in exemple
        run: |
          rm apps/example/.env
          touch apps/example/.env
          echo POSTGRES_URL_NON_POOLING=${{ secrets.POSTGRES_URL_NON_POOLING }} >> apps/example/.env
          echo POSTGRES_PRISMA_URL=${{ secrets.POSTGRES_PRISMA_URL }} >> apps/example/.env
      - name: Reset database
        run: yarn reset-database