name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
on:
  pull_request:
    types:
      - closed
    branches:
      - "main"
jobs:
  Deploy-Production:
    if: startsWith(github.head_ref, 'changeset-release/') && github.event.pull_request.merged == true
    uses: ./.github/workflows/vercel-deploy.yml
    secrets: inherit
    with:
      environment: production
      extra_args: --prod
